#!/usr/bin/env python3
"""Rewrite GNU bc's generated libmath table without an ambient host ed."""

from pathlib import Path


def main() -> None:
    path = Path("libmath.h")
    lines = path.read_text(encoding="ascii").splitlines()
    if len(lines) < 2:
        raise SystemExit("fix-libmath_h: generated table is unexpectedly short")

    # This is the exact transformation in upstream bc/fix-libmath_h:
    # quote every retained line, drop fbc's final marker, and terminate the
    # resulting C array. Keeping it here avoids changing the generated bytes.
    retained = lines[:-1]
    output = []
    for index, line in enumerate(retained):
        prefix = '{"' if index == 0 else '"'
        suffix = '",0}' if index == len(retained) - 1 else '",'
        output.append(f"{prefix}{line}{suffix}")

    path.write_text("\n".join(output) + "\n", encoding="ascii")


if __name__ == "__main__":
    main()
