/* GENERATED by `cargo xtask dump-abi`. Do not edit by hand. */
/* Regenerated by scripts/check-abi-version.sh; drift is a CI failure. */
#ifndef WASM_POSIX_ABI_CONSTANTS_H
#define WASM_POSIX_ABI_CONSTANTS_H

#include <stdint.h>

/* Mirrors wasm_posix_shared::ABI_VERSION. */
#define WASM_POSIX_ABI_VERSION 43u

/* Non-forking spawn syscall number. */
#define WASM_POSIX_SYS_SPAWN 500u

/* Process-fork import mode selectors. */
#define WASM_POSIX_FORK_MODE_FORK 0u
#define WASM_POSIX_FORK_MODE_VFORK 1u

/* Default process-wasm pthread slot declaration. */
#define WASM_POSIX_THREAD_SLOT_DECL_DEFAULT -1

/* Fixed kernel/musl resource-usage wire record size. */
#define WASM_POSIX_RUSAGE_WIRE_SIZE 144u

/* Exact musl termios wire record size. */
#define WASM_POSIX_TERMIOS_SIZE 60u

/* Shared syscall-channel status values. */
#define WASM_POSIX_CHANNEL_STATUS_IDLE 0u
#define WASM_POSIX_CHANNEL_STATUS_PENDING 1u
#define WASM_POSIX_CHANNEL_STATUS_COMPLETE 2u
#define WASM_POSIX_CHANNEL_STATUS_ERROR 3u

/* Shared syscall-channel layout. */
#define WASM_POSIX_CHANNEL_STATUS_OFFSET 0u
#define WASM_POSIX_CHANNEL_STATUS_SIZE 4u
#define WASM_POSIX_CHANNEL_SYSCALL_OFFSET 4u
#define WASM_POSIX_CHANNEL_SYSCALL_SIZE 4u
#define WASM_POSIX_CHANNEL_ARGS_OFFSET 8u
#define WASM_POSIX_CHANNEL_ARGS_COUNT 6u
#define WASM_POSIX_CHANNEL_ARG_SIZE 8u
#define WASM_POSIX_CHANNEL_RETURN_OFFSET 56u
#define WASM_POSIX_CHANNEL_RETURN_SIZE 8u
#define WASM_POSIX_CHANNEL_ERRNO_OFFSET 64u
#define WASM_POSIX_CHANNEL_ERRNO_SIZE 4u
#define WASM_POSIX_CHANNEL_REQUEST_FLAGS_OFFSET 68u
#define WASM_POSIX_CHANNEL_REQUEST_FLAGS_SIZE 4u
#define WASM_POSIX_CHANNEL_REQUEST_FLAG_DEFER_SIGNAL_DELIVERY 4u
#define WASM_POSIX_CHANNEL_REQUEST_FLAG_CANCELLATION_POINT 1u
#define WASM_POSIX_CHANNEL_REQUEST_FLAG_CANCELLATION_WAKE_ALLOWED 2u
#define WASM_POSIX_CHANNEL_REQUEST_FLAGS_KNOWN_MASK 7u
#define WASM_POSIX_CHANNEL_DATA_OFFSET 72u
#define WASM_POSIX_CHANNEL_DATA_SIZE 65536u
#define WASM_POSIX_CHANNEL_HEADER_SIZE 72u
#define WASM_POSIX_CHANNEL_MIN_SIZE 65608u

/* Signal-delivery wire at the end of the channel data buffer. */
#define WASM_POSIX_CHANNEL_SIG_AREA_SIZE 56u
#define WASM_POSIX_CHANNEL_SIG_DELIVERY_SIZE 56u
#define WASM_POSIX_CHANNEL_SIG_WORD_BYTES 4u
#define WASM_POSIX_CHANNEL_SIG_SI_VALUE_BYTES 8u
#define WASM_POSIX_CHANNEL_SIG_OLD_MASK_BYTES 8u
#define WASM_POSIX_CHANNEL_SIG_ALT_SP_BYTES 8u
#define WASM_POSIX_CHANNEL_SIG_ALT_SIZE_BYTES 8u
#define WASM_POSIX_CHANNEL_SIG_BASE_OFFSET 65552u
#define WASM_POSIX_CHANNEL_SIG_SIGNUM_OFFSET 65552u
#define WASM_POSIX_CHANNEL_SIG_HANDLER_OFFSET 65556u
#define WASM_POSIX_CHANNEL_SIG_FLAGS_OFFSET 65560u
#define WASM_POSIX_CHANNEL_SIG_SI_VALUE_OFFSET 65564u
#define WASM_POSIX_CHANNEL_SIG_OLD_MASK_OFFSET 65572u
#define WASM_POSIX_CHANNEL_SIG_SI_CODE_OFFSET 65580u
#define WASM_POSIX_CHANNEL_SIGINFO_WORD_1_OFFSET 65584u
#define WASM_POSIX_CHANNEL_SIGINFO_WORD_2_OFFSET 65588u
#define WASM_POSIX_CHANNEL_SIG_ALT_SP_OFFSET 65592u
#define WASM_POSIX_CHANNEL_SIG_ALT_SIZE_OFFSET 65600u

/* A known request without a lossless layout for this caller. */
#define WASM_POSIX_IOCTL_UNSUPPORTED_SIZE UINT32_MAX

static inline uint32_t
wasm_posix_ioctl_arg_size(uint32_t request, uint32_t pointer_width)
{
switch (request) {
             case 0x00000040u:
return pointer_width == 4u ? 4u :
pointer_width == 8u ? 4u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00000041u:
return pointer_width == 4u ? 0u :
pointer_width == 8u ? 0u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00000042u:
return pointer_width == 4u ? 16u :
pointer_width == 8u ? 16u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00000043u:
return pointer_width == 4u ? 0u :
pointer_width == 8u ? 0u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00000044u:
return pointer_width == 4u ? 32u :
pointer_width == 8u ? 32u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00000045u:
return pointer_width == 4u ? 0u :
pointer_width == 8u ? 0u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00000046u:
return pointer_width == 4u ? 0u :
pointer_width == 8u ? 0u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00000047u:
return pointer_width == 4u ? 8u :
pointer_width == 8u ? 8u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00000048u:
return pointer_width == 4u ? 0u :
pointer_width == 8u ? 0u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00000049u:
return pointer_width == 4u ? 24u :
pointer_width == 8u ? WASM_POSIX_IOCTL_UNSUPPORTED_SIZE :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00004600u:
return pointer_width == 4u ? 160u :
pointer_width == 8u ? 160u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00004601u:
return pointer_width == 4u ? 160u :
pointer_width == 8u ? 160u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00004602u:
return pointer_width == 4u ? 80u :
pointer_width == 8u ? 80u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00004606u:
return pointer_width == 4u ? 160u :
pointer_width == 8u ? 160u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00004b33u:
return pointer_width == 4u ? 1u :
pointer_width == 8u ? 1u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00004b44u:
return pointer_width == 4u ? 4u :
pointer_width == 8u ? 4u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00004b45u:
return pointer_width == 4u ? 0u :
pointer_width == 8u ? 0u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00005000u:
return pointer_width == 4u ? 0u :
pointer_width == 8u ? 0u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00005001u:
return pointer_width == 4u ? 0u :
pointer_width == 8u ? 0u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00005008u:
return pointer_width == 4u ? 0u :
pointer_width == 8u ? 0u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x0000500eu:
return pointer_width == 4u ? 0u :
pointer_width == 8u ? 0u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00005015u:
return pointer_width == 4u ? 0u :
pointer_width == 8u ? 0u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00005016u:
return pointer_width == 4u ? 0u :
pointer_width == 8u ? 0u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00005401u:
return pointer_width == 4u ? 60u :
pointer_width == 8u ? 60u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00005402u:
return pointer_width == 4u ? 60u :
pointer_width == 8u ? 60u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00005403u:
return pointer_width == 4u ? 60u :
pointer_width == 8u ? 60u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00005404u:
return pointer_width == 4u ? 60u :
pointer_width == 8u ? 60u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00005409u:
return pointer_width == 4u ? 0u :
pointer_width == 8u ? 0u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x0000540au:
return pointer_width == 4u ? 0u :
pointer_width == 8u ? 0u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x0000540bu:
return pointer_width == 4u ? 0u :
pointer_width == 8u ? 0u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x0000540eu:
return pointer_width == 4u ? 0u :
pointer_width == 8u ? 0u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x0000540fu:
return pointer_width == 4u ? 4u :
pointer_width == 8u ? 4u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00005410u:
return pointer_width == 4u ? 4u :
pointer_width == 8u ? 4u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00005413u:
return pointer_width == 4u ? 8u :
pointer_width == 8u ? 8u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00005414u:
return pointer_width == 4u ? 8u :
pointer_width == 8u ? 8u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x0000541bu:
return pointer_width == 4u ? 4u :
pointer_width == 8u ? 4u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00005421u:
return pointer_width == 4u ? 4u :
pointer_width == 8u ? 4u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00005422u:
return pointer_width == 4u ? 0u :
pointer_width == 8u ? 0u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00005429u:
return pointer_width == 4u ? 4u :
pointer_width == 8u ? 4u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00005450u:
return pointer_width == 4u ? 0u :
pointer_width == 8u ? 0u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00005451u:
return pointer_width == 4u ? 0u :
pointer_width == 8u ? 0u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00005452u:
return pointer_width == 4u ? 4u :
pointer_width == 8u ? 4u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x0000641eu:
return pointer_width == 4u ? 0u :
pointer_width == 8u ? 0u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x0000641fu:
return pointer_width == 4u ? 0u :
pointer_width == 8u ? 0u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x00008905u:
return pointer_width == 4u ? 4u :
pointer_width == 8u ? 4u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x40045004u:
return pointer_width == 4u ? 4u :
pointer_width == 8u ? 4u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x40045010u:
return pointer_width == 4u ? 4u :
pointer_width == 8u ? 4u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x40045431u:
return pointer_width == 4u ? 4u :
pointer_width == 8u ? 4u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x40086409u:
return pointer_width == 4u ? 8u :
pointer_width == 8u ? 8u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x80045002u:
return pointer_width == 4u ? 4u :
pointer_width == 8u ? 4u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x80045005u:
return pointer_width == 4u ? 4u :
pointer_width == 8u ? 4u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x80045006u:
return pointer_width == 4u ? 4u :
pointer_width == 8u ? 4u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x80045007u:
return pointer_width == 4u ? 4u :
pointer_width == 8u ? 4u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x8004500bu:
return pointer_width == 4u ? 4u :
pointer_width == 8u ? 4u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x8004500fu:
return pointer_width == 4u ? 4u :
pointer_width == 8u ? 4u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x80045010u:
return pointer_width == 4u ? 4u :
pointer_width == 8u ? 4u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x80045017u:
return pointer_width == 4u ? 4u :
pointer_width == 8u ? 4u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x80045430u:
return pointer_width == 4u ? 4u :
pointer_width == 8u ? 4u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x80085013u:
return pointer_width == 4u ? 8u :
pointer_width == 8u ? 8u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x80085014u:
return pointer_width == 4u ? 8u :
pointer_width == 8u ? 8u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x800c5011u:
return pointer_width == 4u ? 12u :
pointer_width == 8u ? 12u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x800c5012u:
return pointer_width == 4u ? 12u :
pointer_width == 8u ? 12u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x8010500cu:
return pointer_width == 4u ? 16u :
pointer_width == 8u ? 16u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0x8010500du:
return pointer_width == 4u ? 16u :
pointer_width == 8u ? 16u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0xc0045002u:
return pointer_width == 4u ? 4u :
pointer_width == 8u ? 4u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0xc0045003u:
return pointer_width == 4u ? 4u :
pointer_width == 8u ? 4u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0xc0045004u:
return pointer_width == 4u ? 4u :
pointer_width == 8u ? 4u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0xc0045005u:
return pointer_width == 4u ? 4u :
pointer_width == 8u ? 4u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0xc0045006u:
return pointer_width == 4u ? 4u :
pointer_width == 8u ? 4u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0xc0045007u:
return pointer_width == 4u ? 4u :
pointer_width == 8u ? 4u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0xc0045009u:
return pointer_width == 4u ? 4u :
pointer_width == 8u ? 4u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0xc004500au:
return pointer_width == 4u ? 4u :
pointer_width == 8u ? 4u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0xc00464afu:
return pointer_width == 4u ? 4u :
pointer_width == 8u ? 4u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0xc00464b4u:
return pointer_width == 4u ? 4u :
pointer_width == 8u ? 4u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0xc00c642du:
return pointer_width == 4u ? 12u :
pointer_width == 8u ? 12u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0xc00c642eu:
return pointer_width == 4u ? 12u :
pointer_width == 8u ? 12u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0xc010640cu:
return pointer_width == 4u ? 16u :
pointer_width == 8u ? 16u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0xc010643au:
return pointer_width == 4u ? 16u :
pointer_width == 8u ? 16u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0xc01064b3u:
return pointer_width == 4u ? 16u :
pointer_width == 8u ? 16u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0xc01464a6u:
return pointer_width == 4u ? 20u :
pointer_width == 8u ? 20u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0xc01864b0u:
return pointer_width == 4u ? 24u :
pointer_width == 8u ? 24u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0xc02064b2u:
return pointer_width == 4u ? 32u :
pointer_width == 8u ? 32u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0xc0246400u:
return pointer_width == 4u ? 36u :
pointer_width == 8u ? WASM_POSIX_IOCTL_UNSUPPORTED_SIZE :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0xc0406400u:
return pointer_width == 4u ? WASM_POSIX_IOCTL_UNSUPPORTED_SIZE :
pointer_width == 8u ? 64u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0xc04064a0u:
return pointer_width == 4u ? 64u :
pointer_width == 8u ? 64u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0xc05064a7u:
return pointer_width == 4u ? 80u :
pointer_width == 8u ? 80u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0xc06864a1u:
return pointer_width == 4u ? 104u :
pointer_width == 8u ? 104u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0xc06864a2u:
return pointer_width == 4u ? 104u :
pointer_width == 8u ? 104u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             case 0xc06864b8u:
return pointer_width == 4u ? 104u :
pointer_width == 8u ? 104u :
WASM_POSIX_IOCTL_UNSUPPORTED_SIZE;
             default:
return 0u;
}
}

#endif /* WASM_POSIX_ABI_CONSTANTS_H */
